In [ ]:
#topper find out average of the marks 80 se kam kinke marks h

In [ ]:
marks = [45, 67, 89, 34, 90]
sum_of_marks = 0
for mark in marks:
    sum_of_marks = sum_of_marks + mark
print(sum_of_marks)
for mark in marks:
    if mark < 80:
        print(mark)




325
45
67
34


In [ ]:
import numpy as np
shoes = np.array([2, 20, 40, 16, 18, 15])

print(shoes.mean())
print(shoes.max())
print(shoes.min())

18.5
40
2


In [ ]:
arr = np.array([45, 67, 89, 34, 90])

print(arr.mean())
print(arr.max())
print(arr.min())

65.0
90
34


In [ ]:
np.array([1, 2, 3,])

array([1, 2, 3])

In [ ]:
age = np.array([23, 56, 54, 32, 21])

print(age.mean())
print(age.max())
print(age.min())

37.2
56
21


In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

ARRAY CREATION

In [ ]:
shoes + 15


array([17, 35, 55, 31, 33, 30])

In [ ]:
arr + 10


array([ 55,  77,  99,  44, 100])

In [ ]:
arr * 4

array([180, 268, 356, 136, 360])

In [ ]:
deep =np.array([4, 10, 16, 24, 32])

print("Addition (+4):", deep + 4)
print("Subtraction (-5):", deep - 5)
print("Multiplication (*8):", deep * 8)
print("Division (/5):", deep / 5)


Addition (+4): [ 8 14 20 28 36]
Subtraction (-5): [-1  5 11 19 27]
Multiplication (*8): [ 32  80 128 192 256]
Division (/5): [0.8 2.  3.2 4.8 6.4]


In [ ]:
deep + 4

array([ 8, 14, 20, 28, 36])

In [ ]:
deep - 5

array([-1,  5, 11, 19, 27])

In [ ]:
deep * 8

array([ 32,  80, 128, 192, 256])

In [ ]:
deep / 5

array([0.8, 2. , 3.2, 4.8, 6.4])

In [ ]:
me_vs_me = np.array([1, 2, 3, 4, 5])
print(me_vs_me[2:4])
print(me_vs_me[4:3:-1])

[3 4]
[5]


ek user se input lena h 5 time with the help of loop
then value ko array me store karna h
then persons agge after 15years before 12 years
the product off ages by 15 and the devide than ages number by 18

In [ ]:
import numpy as np

print("Enter ages of 5 persons:")

a1 = int(input("Age 1: "))
a2 = int(input("Age 2: "))
a3 = int(input("Age 3: "))
a4 = int(input("Age 4: "))
a5 = int(input("Age 5: "))

ages = np.array([a1, a2, a3, a4, a5])


print("\nAfter 15 years:", ages + 15)
print("Before 12 years:", ages - 12)
print("Age * 15:", ages * 15)
print("Age / 18:", ages / 18)

Enter ages of 5 persons:
Age 1: 12
Age 2: 13
Age 3: 14
Age 4: 15
Age 5: 15

After 15 years: [27 28 29 30 30]
Before 12 years: [0 1 2 3 3]
Age * 15: [180 195 210 225 225]
Age / 18: [0.66666667 0.72222222 0.77777778 0.83333333 0.83333333]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr)
print(arr[1:3])

[10 20 30 40]
[20 30]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Mean =", np.mean(arr))
print("Median =", np.median(arr))
print("Standard Deviation =", np.std(arr))

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(a+b)

Mean = 30.0
Median = 30.0
Standard Deviation = 14.142135623730951
[[ 6  8]
 [10 12]]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr)
print(arr[1:3])

[10 20 30 40]
[20 30]


In [ ]:
import math
import datetime
import random

print(math.sqrt(25))
print(datetime.datetime.now())
print(random.randint(1, 100))

5.0
2026-06-07 07:37:10.415921
49


In [ ]:
import math
import datetime
import random
import csv

# Text File Write
file = open("student.txt", "w")
file.write("Deep Dwivedi\n")
file.write("Python Practical")
file.close()

# Text File Read
file = open("student.txt", "r")
print("Text File Content:")
print(file.read())
file.close()

# CSV File Write
with open("student.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["Name", "Marks"])
    writer.writerow(["Deep", 90])
    writer.writerow(["Rahul", 85])

# CSV File Read
print("\nCSV File Content:")
with open("student.csv", "r") as f:
    reader = csv.reader(f)
    for row in reader:
        print(row)

# Math Library
print("\nMath Functions:")
print("Square Root of 25 =", math.sqrt(25))
print("Power =", math.pow(2, 3))

# Datetime Library
print("\nCurrent Date and Time:")
print(datetime.datetime.now())

# Random Library
print("\nRandom Number:")
print(random.randint(1, 100))

Text File Content:
Deep Dwivedi
Python Practical

CSV File Content:
['Name', 'Marks']
['Deep', '90']
['Rahul', '85']

Math Functions:
Square Root of 25 = 5.0
Power = 8.0

Current Date and Time:
2026-06-07 07:40:24.629024

Random Number:
6


In [ ]:
import numpy as np

# 1D Array
arr1 = np.array([10, 20, 30, 40, 50])
print("1D Array:")
print(arr1)

# 2D Array
arr2 = np.array([[1, 2, 3],[4, 5, 6]])
print("\n2D Array:")
print(arr2)

# Slicing
print("\nSlicing:")
print(arr1[1:4])

# Reshaping
arr3 = np.array([1, 2, 3, 4, 5, 6])
reshape_arr = arr3.reshape(2, 3)
print("\nReshaped Array:")
print(reshape_arr)

# Broadcasting
print("\nBroadcasting:")
print(arr1 + 10)

1D Array:
[10 20 30 40 50]

2D Array:
[[1 2 3]
 [4 5 6]]

Slicing:
[20 30 40]

Reshaped Array:
[[1 2 3]
 [4 5 6]]

Broadcasting:
[20 30 40 50 60]


In [ ]:
import pandas as pd

# Series Creation
s = pd.Series([10, 20, 30, 40, 50])

print("Series:")
print(s)

# DataFrame Creation
data = {
    "Name": ["Deep", "Rahul", "Aman"],
    "Age": [18, 19, 20],
    "Marks": [85, 90, 88]
}

df = pd.DataFrame(data)

print("\nOriginal DataFrame:")
print(df)

# Access Column
print("\nName Column:")
print(df["Name"])

# Access Row
print("\nFirst Row:")
print(df.loc[0])

# Add New Column
df["City"] = ["Lucknow", "Kanpur", "Delhi"]

print("\nDataFrame After Adding Column:")
print(df)

# Remove Column
df.drop("Age", axis=1, inplace=True)

print("\nDataFrame After Removing Column:")
print(df)

Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

Original DataFrame:
    Name  Age  Marks
0   Deep   18     85
1  Rahul   19     90
2   Aman   20     88

Name Column:
0     Deep
1    Rahul
2     Aman
Name: Name, dtype: object

First Row:
Name     Deep
Age        18
Marks      85
Name: 0, dtype: object

DataFrame After Adding Column:
    Name  Age  Marks     City
0   Deep   18     85  Lucknow
1  Rahul   19     90   Kanpur
2   Aman   20     88    Delhi

DataFrame After Removing Column:
    Name  Marks     City
0   Deep     85  Lucknow
1  Rahul     90   Kanpur
2   Aman     88    Delhi


In [ ]:
import pandas as pd

# Creating DataFrame
data = {
    "Name": ["Deep", "Rahul", "Aman", "Riya", "Priya"],
    "Department": ["IT", "IT", "HR", "HR", "IT"],
    "Marks": [85, 90, 78, 88, 95]
}

df = pd.DataFrame(data)

print("Original DataFrame")
print(df)

# Filtering
print("\nStudents having Marks > 85")
filtered_df = df[df["Marks"] > 85]
print(filtered_df)

# Sorting
print("\nSorting by Marks")
sorted_df = df.sort_values(by="Marks", ascending=False)
print(sorted_df)

# Grouping
print("\nGroup By Department")
grouped = df.groupby("Department")
print(grouped["Marks"].sum())

# Aggregation
print("\nAggregation Functions")
result = df.groupby("Department").agg({
    "Marks": ["sum", "mean", "max", "min", "count"]
})

print(result)

Original DataFrame
    Name Department  Marks
0   Deep         IT     85
1  Rahul         IT     90
2   Aman         HR     78
3   Riya         HR     88
4  Priya         IT     95

Students having Marks > 85
    Name Department  Marks
1  Rahul         IT     90
3   Riya         HR     88
4  Priya         IT     95

Sorting by Marks
    Name Department  Marks
4  Priya         IT     95
1  Rahul         IT     90
3   Riya         HR     88
0   Deep         IT     85
2   Aman         HR     78

Group By Department
Department
HR    166
IT    270
Name: Marks, dtype: int64

Aggregation Functions
           Marks                    
             sum  mean max min count
Department                          
HR           166  83.0  88  78     2
IT           270  90.0  95  85     3


In [ ]:
import pandas as pd

# Import Employee CSV File
df = pd.read_csv("/content/employees.csv")

print("Employee Data")
print(df)

# Check Missing Values
print("\nMissing Values")
print(df.isnull())

# Fill Missing Values
df1 = df.fillna("Not Available")

print("\nAfter fillna()")
print(df1)

# Remove Missing Values
df2 = df.dropna()

print("\nAfter dropna()")
print(df2)

# Save File
df.to_csv("new_employees.csv", index=False)

print("\nFile Saved Successfully")

Employee Data
    First Name  Last Name                                    Email  \
0         Jose      Lopez           joselopez0944@slingacademy.com   
1        Diane     Carter         dianecarter1228@slingacademy.com   
2        Shawn     Foster         shawnfoster2695@slingacademy.com   
3       Brenda     Fisher        brendafisher3185@slingacademy.com   
4         Sean     Hunter          seanhunter4753@slingacademy.com   
..         ...        ...                                      ...   
315   Michelle     Hooper    michellehooper315396@slingacademy.com   
316     Steven      Lewis       stevenlewis316274@slingacademy.com   
317      Kevin  Rodriguez    kevinrodriguez317974@slingacademy.com   
318  Alexandra       Bell     alexandrabell318109@slingacademy.com   
319   Courtney   Mcdaniel  courtneymcdaniel319568@slingacademy.com   

                      Phone  Gender  Age                  Job Title  \
0      +1-971-533-4552x1542    male   25            Project Manager   
1  